-- Rooms table to list ongoing lives
create table if not exists public.rooms (
  id text primary key,
  title text not null,
  host_identity text,
  live boolean default false,
  viewers integer default 0,
  likes integer default 0,
  thumbnail_url text,
  created_at timestamp with time zone default now()
);

-- Chat messages per room
create table if not exists public.chat_messages (
  id bigint generated by default as identity primary key,
  room_id text not null references public.rooms(id) on delete cascade,
  sender text not null,
  message text not null,
  created_at timestamp with time zone default now()
);

-- Index for fast lookups
create index if not exists chat_room_idx on public.chat_messages(room_id, created_at desc);

-- RPC to increment viewers atomically
create or replace function public.rpc_increment_viewers(room_id text, delta integer)
returns integer
language sql
as $
  update public.rooms
  set viewers = greatest(0, viewers + delta)
  where id = room_id
  returning viewers;
$;

grant execute on function public.rpc_increment_viewers(text, integer) to anon, authenticated;

-- Optional RPC to increment likes atomically
create or replace function public.rpc_increment_likes(room_id text, delta integer)
returns integer
language sql
as $
  update public.rooms
  set likes = greatest(0, likes + delta)
  where id = room_id
  returning likes;
$;

grant execute on function public.rpc_increment_likes(text, integer) to anon, authenticated;

-- Realtime enable
alter publication supabase_realtime add table rooms;
alter publication supabase_realtime add table chat_messages;