-- Rooms table to list ongoing lives
create table if not exists public.rooms (
  id text primary key,
  title text not null,
  host_identity text,
  live boolean default false,
  viewers integer default 0,
  created_at timestamp with time zone default now()
);

-- Chat messages per room
create table if not exists public.chat_messages (
  id bigint generated by default as identity primary key,
  room_id text not null references public.rooms(id) on delete cascade,
  sender text not null,
  message text not null,
  created_at timestamp with time zone default now()
);

-- Index for fast lookups
create index if not exists chat_room_idx on public.chat_messages(room_id, created_at desc);

-- Realtime enable
alter publication supabase_realtime add table rooms;
alter publication supabase_realtime add table chat_messages;